api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"

  traefik:
    address: ":8888"
providers:
  consulCatalog:
    endpoint:
      address: "127.0.0.1:8500"
    consulCatalog:
      refreshInterval: 5s
      exposedByDefault: false
      endpoint:
        address: 127.0.0.1.8500