services:
  dbserver:
    image: postgres:17.7-alpine3.23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    volumes:
      - "C:/Users/emilv/OneDrive/Documents/ProgDistribuida/db-distribuida:/var/lib/postgresql/data"
    ports:
      - 54321:5432

  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    expose:
      - 8500
    ports:
      - 8500:8500

  authors:
    image: app-authors
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
#   este expose es comunicacion dentro del contenedor
    expose:
      - 8080
    ports:
      - 8888:8080
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul

  books:
    image: app-books
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
#   este expose es comunicacion dentro del contenedor
    expose:
      - 8080
    ports:
      - 8889:8080
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul
