services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config:/etc/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090

  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
        DATA_SOURCE_URI: dbserver:5432/distribuida?sslmode=disable
        DATA_SOURCE_USER: postgres
        DATA_SOURCE_PASS: postgres
    expose:
        - 9187

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    expose:
      - 3000
  dbserver:
    image: postgres:17.7-alpine3.23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    volumes:
      - "C:/Users/emilv/OneDrive/Documents/ProgDistribuida/db-distribuida:/var/lib/postgresql/data"
#    ports:
#      - 54321:5432

  proxy:
    image: traefik:3.6
    command: |
      --api.insecure=true
      --api.dashboard=true
      --providers.consulCatalog
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.endpoint.address=consul:8500
      --metrics.prometheus=true
      --metrics.prometheus.entryPoint=metrics
      --entryPoints.metrics.address=:8082
    ports:
      - 8888:8080
      - 8080:80
      - 8082:8082
    depends_on:
      - consul
      - prometheus

  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    expose:
      - 8500
    ports:
      - 8500:8500

  customers:
    image: emil2245/app-customers
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbserver:5432/distribuida
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    expose:
      - 8080
#    deploy:
#      replicas: 1
    depends_on:
      - dbserver
      - prometheus
      - consul

  authors:
    image: emil2245/app-authors
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
#   este expose es comunicacion dentro del contenedor
    expose:
      - 8080
    ports:
      - 8889:8080
#    deploy:
#      replicas: 1
    depends_on:
      - dbserver
      - prometheus
      - consul

  books:
    image: emil2245/app-books:latest
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_HTTP_HOST: 0.0.0.0

      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    expose:
      - 8080
#    ports:
#      - 8889:8080
#    deploy:
#      replicas: 1
    depends_on:
      - dbserver
      - prometheus
      - consul

#  react:
#    image: emil2245/app-web-react
#    entrypoint: >
#      sh -c "curl --request PUT
#      --data '{\"Name\": \"app-web-react\", \"Address\": \"react\", \"Port\": 80, \"Tags\": [\"traefik.enable=true\", \"traefik.http.routers.react.rule=PathPrefix(`/`)\", \"traefik.http.routers.react.priority=1\"]}'
#      http://consul:8500/v1/agent/service/register && nginx -g 'daemon off;'"
#    depends_on:
#      - consul

  react:
    image: emil2245/app-web-react
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=PathPrefix(`/`)"
      - "traefik.http.routers.react.entrypoints=web"
      - "traefik.http.routers.react.priority=1"
      - "traefik.http.services.react.loadbalancer.server.port=80"

