services:
  dbserver:
    image: postgres:17.7-alpine3.23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    volumes:
      - "C:/Users/emilv/OneDrive/Documents/ProgDistribuida/db-distribuida:/var/lib/postgresql/data"
#    ports:
#      - 54321:5432

  proxy:
    image: traefik:3.6
    command: |
      --api.insecure=true
      --api.dashboard=true
      --providers.consulCatalog
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.endpoint.address=consul:8500
    ports:
      - 8888:8080
      - 8080:80
    depends_on:
      - consul


  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    expose:
      - 8500
    ports:
      - 8500:8500

  customers:
    image: emil2245/app-customers
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbserver:5432/distribuida
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    expose:
      - 8080
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul

  authors:
    image: emil2245/app-authors
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
#   este expose es comunicacion dentro del contenedor
    expose:
      - 8080
#    ports:
#      - 8888:8080
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul

  books:
    image: emil2245/app-books
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
#   este expose es comunicacion dentro del contenedor
    expose:
      - 8080
#    ports:
#      - 8889:8080
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul
