server:
  port: 9090
spring:
  application:
    name: app-recommend
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health/readiness
        health-check-interval: 10s
  ai:
    openai:
      api-key: YOUR_OPEN
      base-url: http://localhost:8080
      chat:
        options:
          model: llama-3.1-1B-instruct-q8_0.gguf

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
