# App Customers (Spring Boot) - Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-customers
  namespace: book-store
  labels:
    app: app-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-customers
  template:
    metadata:
      labels:
        app: app-customers
    spec:
      containers:
        - name: app-customers
          image: emil2245/app-customers:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresq:5432/distribuida
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-customers
  namespace: book-store
spec:
  type: ClusterIP
  selector:
    app: app-customers
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
