---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-proxy-nginx
  namespace: etverkade-dev
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events { worker_connections 1024; }
    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      upstream react { server app-react:80; }
      upstream books { server app-books:8080; }
      server {
        listen 8080;
        
        location /app-books/ {
          proxy_pass http://books/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /books {
          proxy_pass http://books;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
          proxy_pass http://react;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-proxy
  namespace: etverkade-dev
  labels:
    app: front-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-proxy
  template:
    metadata:
      labels:
        app: front-proxy
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:alpine-slim
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
      volumes:
        - name: nginx-config
          configMap:
            name: front-proxy-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: front-proxy
  namespace: etverkade-dev
spec:
  type: ClusterIP
  selector:
    app: front-proxy
  ports:
    - name: http-proxy
      protocol: TCP
      port: 80
      targetPort: 8080
