---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: front
  namespace: etverkade-dev
spec:
  to:
    kind: Service
    name: front-proxy
    weight: 100
  port:
    targetPort: http-proxy
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: etverkade-dev
spec:
  to:
    kind: Service
    name: grafana
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: edge
  wildcardPolicy: None
